-- Generated by HyprMod

-- Settings
hl.config({
    dwindle = {
        smart_split = false,
    },
    general = {
        border_size = 1,
        col = {
            active_border = "0xfff6f5f4",
            inactive_border = "0xff87a7da",
        },
        gaps_in = 2,
        gaps_out = 6,
        resize_on_border = true,
    },
    input = {
        touchpad = {
            natural_scroll = true,
        },
    },
})

-- Monitors
hl.monitor({
    output = "eDP-1",
    disabled = false,
    mode = "1920x1080@60.00Hz",
    position = "0x0",
    scale = 1.25,
    cm = "srgb",
})

-- Keybinds
hl.unbind("SUPER + Q")
hl.bind("SUPER + Q", hl.dsp.window.close())
hl.unbind("SUPER + Return")
hl.bind("SUPER + Return", hl.dsp.exec_cmd("kitty"))
hl.unbind("SUPER + B")
hl.bind("SUPER + B", hl.dsp.exec_cmd("brave"))
hl.unbind("SUPER + H")
hl.bind("SUPER + H", hl.dsp.exec_cmd("hyprmod"))
hl.unbind("SUPER + space")
hl.bind("SUPER + space", hl.dsp.exec_cmd("rofi -show drun -show-icons"))
hl.unbind("XF86MonBrightnessUp")
hl.bind("F5", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), {
    repeating = true,
})
hl.unbind("XF86MonBrightnessDown")
hl.bind("F6", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), {
    repeating = true,
})
